export const clothes = [
  {
    clothes_aid: 1,
    clothes_title: "Stitched Football Trackpant Indigo",
    clothes_category: "Pants",
    clothes_price: "7,700.00",
    clothes_image: "na-card-a1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 2,
    clothes_title: "Pants v1",
    clothes_category: "Pants",
    clothes_price: "7,700.00",
    clothes_image: "pants-1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 3,
    clothes_title: "Pants v2",
    clothes_category: "Pants",
    clothes_price: "7,700.00",
    clothes_image: "pants-2.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 4,
    clothes_title: "Creators Club Lounge Tee Forest",
    clothes_category: "T-Shirts",
    clothes_price: "4,150.00",
    clothes_image: "na-card-a2.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 5,
    clothes_title: "Creators Club Lounge Tee Vintage White",
    clothes_category: "T-Shirts",
    clothes_price: "4,150.00",
    clothes_image: "na-card-a3.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 6,
    clothes_title: "Sweater Crop",
    clothes_category: "Sweater",
    clothes_price: "3,600.00",
    clothes_image: "sweater-1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 7,
    clothes_title: "Sweater v2",
    clothes_category: "Sweater",
    clothes_price: "3,600.00",
    clothes_image: "sweater-2.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 8,
    clothes_title: "Jacket v1",
    clothes_category: "Jacket",
    clothes_price: "4,600.00",
    clothes_image: "jacket-1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 9,
    clothes_title: "Jacket v2",
    clothes_category: "Jacket",
    clothes_price: "4,600.00",
    clothes_image: "jacket-2.jpg",
    clothes_is_active: true,
  },

];
